[master]
app-master ansible_host=192.168.56.101

[workers]
app-worker1 ansible_host=192.168.56.102
app-worker2 ansible_host=192.168.56.103

[db]
app-db ansible_host=192.168.56.104

[backup]
app-backup ansible_host=192.168.56.105

[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3